- name: Get primordial master IP
  set_fact:
    primordial_ip: "{{ hostvars | dict2items
      | selectattr('value.var_primordial_master', 'defined')
      | selectattr('value.var_primordial_master', 'equalto', true)
      | map(attribute='value.server_ip') | list | first }}"


- name: Install Worker Node
  shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - agent --server https://{{ primordial_ip }}:6443 \
      --docker
  become: true
