---
- name: Install and configure HAProxy
  hosts: vm01
  gather_facts: true
  become: true
  vars:
    templates_dir: "{{ playbook_dir }}/../templates"

  roles:
    - role: haproxy-install
      tags: [haproxy-install]