---
- name: Install the K3S Cluster
  hosts: all
  gather_facts: yes
  become: true

  pre_tasks:
  
    - name: Ensure ~/.kube directory exists
      command: "mkdir -p ~/.kube"
      delegate_to: localhost
      become: false
      changed_when: true
      run_once: true

    - name: Ensure ~/.kube directory is empty
      shell: "rm -rf ~/.kube/*"
      delegate_to: localhost
      become: false
      changed_when: true
      run_once: true


  roles:
    # - role: docker-install
    #   tags: [docker-install]
      
    - role: master-primordial-install
      tags: [master-primordial-install]
      when: var_primordial_master is defined

    - role: retrive-kubeconfig
      tags: [retrive-kubeconfig]
      when: var_primordial_master is defined

    - role: master-install
      tags: [master-install]
      when: var_master is defined and var_primordial_master is not defined
    
    - role: worker-install
      tags: [worker-install]
      when: var_worker is defined

  

