---
- name: Install the K3S Cluster
  hosts: all
  gather_facts: yes
  become: true

  pre_tasks:
  
    - name: Ensure ~/.kube directory exists
      command: "mkdir -p ~/.kube"
      delegate_to: localhost
      become: false

    - name: Ensure ~/.kube directory is empty
      shell: "rm -rf ~/.kube/*"
      delegate_to: localhost
      become: false


  roles:
    - role: docker-install
      tags: [docker-install]

    - role: master-install
      tags: [master-install]
    
    - role: worker-install
      tags: [worker-install]

  

