---
- name: Uninstall K3s
  hosts: all
  gather_facts: true

  roles:
    - role: kill_docker
      tags: [ kill_docker ]

    - role: uninstall_master
      tags: [ uninstall_master ]
      when: var_master is defined  

    - role: uninstall_worker
      tags: [ uninstall_worker ]
      when: var_worker is defined  

   